[phases.setup]
cmds = [
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install virtualenv"
]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.start]
cmd = "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0"